/*
 * This source file was generated by the Gradle 'init' task
 */
package financetracker;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    //TODO: create tests
}
